/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeProject_GUI;

import EmployeeProject_DButil.DBConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class SelectOption extends javax.swing.JFrame {

    /**
     * Creates new form SelectOption
     */
    public SelectOption() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbtnAddEmp = new javax.swing.JRadioButton();
        rbtnSearch = new javax.swing.JRadioButton();
        rbtnShow = new javax.swing.JRadioButton();
        rbtnQuit = new javax.swing.JRadioButton();
        btnTask = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JRadioButton();
        jbtnDelete = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("              Select An Option ");

        rbtnAddEmp.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbtnAddEmp);
        rbtnAddEmp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtnAddEmp.setForeground(new java.awt.Color(255, 255, 255));
        rbtnAddEmp.setText("Add Emplyee");

        rbtnSearch.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbtnSearch);
        rbtnSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSearch.setText("Search Employee");

        rbtnShow.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbtnShow);
        rbtnShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtnShow.setForeground(new java.awt.Color(255, 255, 255));
        rbtnShow.setText("Show All Employee");

        rbtnQuit.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbtnQuit);
        rbtnQuit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtnQuit.setForeground(new java.awt.Color(255, 255, 255));
        rbtnQuit.setText("Quit");

        btnTask.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTask.setText("Do Task");
        btnTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaskActionPerformed(evt);
            }
        });

        jbtnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jbtnUpdate);
        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jbtnUpdate.setText("Update Employee Details");

        jbtnDelete.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jbtnDelete);
        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDelete.setText("Delete Employee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnSearch)
                            .addComponent(rbtnAddEmp)
                            .addComponent(rbtnShow)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnTask, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addComponent(rbtnQuit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnAddEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnShow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnDelete)
                .addGap(10, 10, 10)
                .addComponent(rbtnQuit)
                .addGap(18, 18, 18)
                .addComponent(btnTask, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaskActionPerformed
        // TODO add your handling code here:
        if(validateInput()==false){
            JOptionPane.showMessageDialog(null, "Please Select first","No Selection",JOptionPane.INFORMATION_MESSAGE);
             return;
        }
        
        if(rbtnAddEmp.isSelected()){
            AddEmpFrame fr=new AddEmpFrame();
            fr.setVisible(true);
        }
        else if(rbtnSearch.isSelected()){
            SearchEmpFrame fr=new SearchEmpFrame();
            fr.setVisible(true);
        }
        else if(rbtnShow.isSelected()){
            ViewAllFrame fr=new ViewAllFrame();
            fr.setVisible(true);
        }
        else if(jbtnDelete.isSelected()){
            DeleteEmpFrame fr=new DeleteEmpFrame();
            fr.setVisible(true);
        }
        else if(jbtnUpdate.isSelected()){
            UpdateEmpFrame fr=new UpdateEmpFrame();
            fr.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Thank you for using the app", "Thanks",JOptionPane.INFORMATION_MESSAGE);
            DBConnection.closeConnetion();
            System.exit(0);
        }  
        this.dispose();        
    }//GEN-LAST:event_btnTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTask;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jbtnDelete;
    private javax.swing.JRadioButton jbtnUpdate;
    private javax.swing.JRadioButton rbtnAddEmp;
    private javax.swing.JRadioButton rbtnQuit;
    private javax.swing.JRadioButton rbtnSearch;
    private javax.swing.JRadioButton rbtnShow;
    // End of variables declaration//GEN-END:variables

    private boolean validateInput() {
      if(rbtnAddEmp.isSelected()==false && rbtnSearch.isSelected()==false && jbtnDelete.isSelected()==false && jbtnUpdate.isSelected()==false&& rbtnShow.isSelected()==false && rbtnQuit.isSelected() ==false)
           return false;
      return true;
    }
}
